version: 2
jobs:
  test:
    docker:
      - image: norisaka/cobjava
    steps:
      - checkout
      - run: bash compile.sh
      - run: bash run.sh
      - run: mkdir /tmp/test-results
      - run: cp RESULT-SEQ /tmp/test-results
      - run: cp ZINKOMITSUDO2.java  /tmp/test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/test-results
      #    destination: prefix
workflows:
  version: 2
  test:
    jobs:
      - test
